In [ ]:
#Day-17 
#Agenda  :    Python Bulit-in Libraries:
                 1. Numpy
                 2. Pandas
                 3. MatPolt Lib
#Numpy:
Numpy is an Open Source Library available in Python.

#It provides High -level functions to perform mathematical operations on numerical data.
Author: Travis Oliphant
First Release : 1995 
Written in- Python Programming,C

#Features
Numpy stands - for Numrical Python (Numpy-num+py)
1. Its contains powerful N-dimensional Object 
2. Fourier Transforms and shapes manipulation.
3. Linear Algebra and random number generation.

In [ ]:
#How to Install Numpy Package in your System:
pip install numpy   - #IDLE Users

conda install -c anaconda numpy  - #anaconda users

#How to import and use numpy
import numpy as np

In [2]:
#How to import and use numpy
import numpy as np

#to check version
print(np.__version__)

1.16.4


In [14]:
#how to create Numpy arrays: (single-dimensional arrays)
#We create Numpy arrays using Lists or Nested lists.
import numpy as np
a = np.array([1,2,3])
print(a)
print(a.shape)  #to find the shape of numpy array
print(a.dtype)  # to find datatype of numpy array
a

[1 2 3]
(3,)
int32


array([1, 2, 3])

In [13]:
#numpy arrays with float values
b = np.array([1.1,3.5,6.8])
print(b.dtype)
print(b.shape)

float64
(3,)


In [18]:
#How to create 2D numpy Arrays:
import numpy as np
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d)
print(d.shape)
print(d.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int32


In [38]:
#Numpy operations:
#zeros: (its used to create a matrix full of zeros)
#syntax: 
#numpy.zeros(shape,dtype=float,order="C")
import numpy as np
print(np.zeros((2,2)))
print(np.zeros((4,4)))

[[0. 0.]
 [0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [32]:
#np.ones() functions:
#syntax: 
#numpy.zeros(shape,dtype=float,order="C")

print(np.ones([1,2,3]))   # To give the rows and coloums order
print(np.ones((1,2,3),dtype=np.int16))  

[[[1. 1. 1.]
  [1. 1. 1.]]]
[[[1 1 1]
  [1 1 1]]]


In [42]:
print(np.ones((2,3)))
print(np.ones((3,2)))

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [49]:
#reshape of numpy arrays
#reshape():
#syntax:
             #numpy.reshape(a,newshape,order="C")
             #a - array that you what to change
import numpy as np
a = np.array([[1,2,3],[5,6,8]])
print(a)
print(a.shape)
b=a.reshape(3,2)
print(b)
print(b.shape)
print(b.flatten())

[[1 2 3]
 [5 6 8]]
(2, 3)
[[1 2]
 [3 5]
 [6 8]]
(3, 2)
[1 2 3 5 6 8]


In [52]:
#Hstack and Vstack: (for appending the data in horizontal and vertically)
#Hstack:
import numpy as np
a = np.array([[1,3,5]])
b = np.array([[4,6,8]])
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[[1 3 5 4 6 8]]
[[1 3 5]
 [4 6 8]]


In [54]:
#Generate random numbers:
#numpy.random.normal(loc,scale,size)
# Loc- mean of distribution
#scale - standard deviation
#size- number of retuns
# To generate random number from normal distribution.
normal_array = np.random.normal(5,0.5,10)
print(normal_array)

[4.41895406 5.1965508  4.91275274 4.90870586 4.66131123 5.02896264
 4.55874946 4.73970913 5.27904588 4.63092246]


In [ ]:
#arange() function:
Its used to returns an ndarray(n-dimensional array) object that contains evenly 
spaced values within a defined internal.
#syatax:

numpy.arange(start,stop,size)

In [67]:
import numpy as np
print(np.arange(1,11))

print(np.arange(1,11,2))
print(np.linspace(1.0,5.0,num=10,endpoint=False)) #for generationg even spaced samples
print(np.logspace(3.0,4.0,num=4))   #for even space samples on log scale

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6]
[ 1000.          2154.43469003  4641.58883361 10000.        ]


In [81]:
#slicing on numpy arrays:
import numpy as np
a=np.array([(1,2,3,5),(3,5,6,8),[50,60,90,100]])
print(a[0,2])
print(a[1,3])
print(a[0, 2], a[1, 2])   #boomika logic
print(a[0:,2])      #my logic
print(a[0:,1])  #prasanna kumar logic
print(a[1,1],a[1,3])   #naveen logic
print(a[0:2,3])

3
8
3 6
[ 3  6 90]
[ 2  5 60]
5 8
[5 8]


In [98]:
#Max/min:
import numpy as np
a = np.array([[1,2,3,4,5],[4,5,6,7,8]])
b = np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(a.max())
print(a.min())
print(a.sum())
print(a.sum(axis=0))  #column based
print(a.sum(axis=1)) #row based
print(np.sqrt(a))
print(np.std(a))
print(a+b)
print(a-b)
print(a*b)
print(a/b)

8
1
45
[ 5  7  9 11 13]
[15 30]
[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.         2.23606798 2.44948974 2.64575131 2.82842712]]
2.0615528128088303
[[ 2  4  6  8 10]
 [ 8 10 12 14 16]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[ 1  4  9 16 25]
 [16 25 36 49 64]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#Pandas in Python:
Pandas is an opensource library in python that allows to you perform 
                (i)    Data manipuation,
                (ii)   Data analysis
                (iii)  Data Cleaning
1. its built on top of Numpy Packages,Pandas need to Numpy arrays data to operate
2. its a elegant solution for time series Data
            1. Population of Data
            2. any Company production Growth
    #Author : Wes McKinney
    #First Release: version 0.23 July,2018
    #Written in : Python
    
#Why use pandas?
 Data Scientics use pandas for its
     1. easily handles missing data
     2. flexible way to slice the data.
     3. Provides powerful time series tool to work with Data Frames.

In [ ]:
#How to install pandas:
pip install pandas

In [ ]:

#What is Data frame:(Pandas Data Structures (Data Frame and Data Series))
Df is 2d- array ,with labeled axes (rows and columns) to store the data.
 its contains tabular data.
   #ex: item     price
    0   A        50
    1   B       100
#Data Series:
 A series is a 1- D data structure. It can have any data type values
     like integer, float, and string
    #ex:
    0    1.0
    1   2.0
    2   3.0
    dtype: float64

In [107]:
# How to create Data series:
import pandas as pd
s1 =pd.Series([1,2,3])
s2= pd.Series([1.,2.,3.],index=["a","b","c"])
s3 = pd.Series([1,2,np.nan])   #missing value as "NaN"
print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
dtype: int64
a    1.0
b    2.0
c    3.0
dtype: float64
0    1.0
1    2.0
2    NaN
dtype: float64


In [18]:
#How to create Data Frames:
#Numpy to Pandas
import numpy as np
#a = [[1,3],[5,6]]
df = pd.DataFrame([[1,3],[5,6]])
print(df)
df
#pandas to numpy
df_to_numpy = np.array(df)
df_to_numpy

   0  1
0  1  3
1  5  6


array([[1, 3],
       [5, 6]], dtype=int64)

In [118]:
#dataframe with Dictionary Values:
import pandas as pd
dic = {'Name':["surya","apssdc","python"],"values":[50,60,100]}
pd.DataFrame(data=dic,index=["1","2","3"])

Name  values
1   surya      50
2  apssdc      60
3  python     100

In [ ]:
#Inspecting the Data:
# we can check the head or tail of the dataset with head(),or tail() functions:

In [21]:
#How to read csv files (Data Sets):
import pandas as pd
df = pd.read_csv("Employee_data.csv")
df

Emp ID Name Prefix First Name Middle Initial   Last Name Gender  \
0      158108         Mr.    Bernard              N   Weatherly      M   
1      863655         Ms.     Cordia              M       Knopp      F   
2      343966         Mr.     Burton              C         Jin      M   
3      389958         Mr.     Lauren              O       Guzzi      M   
4      291208       Prof.     Carter              C        Hunt      M   
5      636449         Mr.     Isaiah              Y     Magwood      M   
6      731529         Mr.       Hugh              N     Chavira      M   
7      331652       Prof.     Lucius              C    Moorhead      M   
8      930753         Ms.      Deane              I       Keown      F   
9      212822        Mrs.    Joannie              E     Wolters      F   
10     406273         Ms.  Christene              L     Mccaleb      F   
11     984721        Mrs.     Alline              V     Kushner      F   
12     161868        Hon.      Vicki              Y    Hargrave      F   
13     948514        Mrs.   Julienne              A      Merkel      F   
14     467644         Mr.      Keven              C       Thole      M   
15     439713         Ms.    Eusebia              N    Waldroup      F   
16     435127         Ms.  Veronique              E   Eccleston      F   
17     880688        Mrs.       Sean              W     Richman      F   
18     415263         Ms.       Lala              C     Marquez      F   
19     697769        Hon.     Derick              A       Macey      M   
20     469336        Mrs.        Eda              O       Brase      F   
21     352932         Mr.     Willis              D    Weissman      M   
22     829478         Ms.     Mariam              F    Pinheiro      F   
23     517840         Mr.     Malcom              L     Meister      M   
24     709861        Mrs.      Holli              G    Ethridge      F   
25     751367         Dr.       Cole              N      Poling      M   
26     940813         Dr.      Ahmad              V       Lynde      M   
27     930580         Dr.    Mariano              F       Leary      M   
28     120297         Ms.    Tawanda              E    Buchanon      F   
29     796317        Hon.   Nickolas              G      Grossi      M   
...       ...         ...        ...            ...         ...    ...   
49970  786901         Mr.    Stewart              Z       Mantz      M   
49971  279036       Prof.     Dewitt              U     Ekstrom      M   
49972  525884         Ms.    Candyce              Z      Gardea      F   
49973  226692         Mr.       Ezra              P       Loman      M   
49974  189099         Mr.   Raymundo              T       Hagar      M   
49975  162936         Mr.   Norberto              X      Basham      M   
49976  602698        Mrs.     Desire              R       Keefe      F   
49977  144035        Hon.     Serena              X     Fussell      F   
49978  215934        Hon.    William              Z        Amen      M   
49979  968064         Ms.    Ginette              Z      Holden      F   
49980  197081         Ms.        Pei              D         Fey      F   
49981  887146        Drs.     Leanne              J      Uecker      F   
49982  518937         Mr.      Jarod              C        Rech      M   
49983  684273         Ms.     Hiroko              L      Holton      F   
49984  283912         Mr.       Theo              T    Blanford      M   
49985  475827         Ms.    Beverly              D      Jewell      F   
49986  649810         Mr.       Juan              L       Coury      M   
49987  267565         Ms.     Lenora              S      Kulick      F   
49988  939635        Hon.     Delora              H       Corle      F   
49989  514084       Prof.    Rolando              S   Oestreich      M   
49990  963209        Mrs.      Billy              I     Phillip      F   
49991  931753         Ms.     Grayce              J       Vella      F   
49992  5783

In [23]:
#head(): its reads the data rows from top 
df.head(3)
df.head(15)

Emp ID Name Prefix First Name Middle Initial  Last Name Gender  \
0   158108         Mr.    Bernard              N  Weatherly      M   
1   863655         Ms.     Cordia              M      Knopp      F   
2   343966         Mr.     Burton              C        Jin      M   
3   389958         Mr.     Lauren              O      Guzzi      M   
4   291208       Prof.     Carter              C       Hunt      M   
5   636449         Mr.     Isaiah              Y    Magwood      M   
6   731529         Mr.       Hugh              N    Chavira      M   
7   331652       Prof.     Lucius              C   Moorhead      M   
8   930753         Ms.      Deane              I      Keown      F   
9   212822        Mrs.    Joannie              E    Wolters      F   
10  406273         Ms.  Christene              L    Mccaleb      F   
11  984721        Mrs.     Alline              V    Kushner      F   
12  161868        Hon.      Vicki              Y   Hargrave      F   
13  948514        Mrs.   Julienne              A     Merkel      F   
14  467644         Mr.      Keven              C      Thole      M   

                         E Mail       Father's Name      Mother's Name  \
0   bernard.weatherly@gmail.com    Wilbur Weatherly    Liana Weatherly   
1      cordia.knopp@hotmail.com        Wilson Knopp      Darline Knopp   
2          burton.jin@yahoo.com         Richard Jin       Willette Jin   
3        lauren.guzzi@yahoo.com         Blair Guzzi      Shanika Guzzi   
4       carter.hunt@hotmail.com          Jamal Hunt         Kaila Hunt   
5    isaiah.magwood@comcast.net       Bryan Magwood   Joaquina Magwood   
6         hugh.chavira@yahoo.ca         Don Chavira      Aline Chavira   
7     lucius.moorhead@yahoo.com  Marcelino Moorhead   Jillian Moorhead   
8       deane.keown@hotmail.com          Gale Keown          Dia Keown   
9   joannie.wolters@yahoo.co.in     Nicolas Wolters  Margarett Wolters   
10  christene.mccaleb@gmail.com     Freddie Mccaleb     Eladia Mccaleb   
11       alline.kushner@aol.com      Harlan Kushner     Linsey Kushner   
12   vicki.hargrave@hotmail.com     Judson Hargrave    Shonda Hargrave   
13  julienne.merkel@hotmail.com        Jesse Merkel      Deetta Merkel   
14        keven.thole@gmail.com        Ismael Thole       Jonell Thole   

   Mother's Maiden Name  ...          SSN    Phone No.        Place Name  \
0                 Grams  ...  701-18-3166  423-283-5871      Shelbyville   
1                 Diana  ...  115-98-5006  205-200-6563       Eight Mile   
2                Garcia  ...  176-86-8865  479-568-5620            Timbo   
3               Beerman  ...  258-99-4279  216-582-0466      Bladensburg   
4              Starrett  ...  469-57-4080  231-981-5020        Fruitport   
5                    Hu  ...  474-55-7066  212-550-9226      Cowlesville   
6                  Blea  ...  434-99-1950  218-249-1088        Ellsworth   
7                 Focht  ...  157-23-2905  210-461-1191   Corpus Christi   
8              Benjamin  ...  613-87-9535  209-670-9745  West Sacramento   
9                  Rosa  ...  198-84-6571  304-464-6109          Century   
10              Clinard  ...  454-99-1093  236-360-0823        Arlington   
11             Houseman  ...  007-11-7619  503-656-0140            Oxbow   
12                 Leib  ...  481-41-3855  206-408-3056          Spokane   
13               Canady  ...  223-99-2411  480-729-0845  Apache Junction   
14          Steigerwald  ...  247-99-6318  319-820-9084         Houghton   

       County             City State    Zip     Region    User Name  \
0     Bedford      Shelbyville    TN  37160      South  bnweatherly   
1      Mobile       Eight Mile    AL  36613      South      cmknopp   
2       Stone            Timbo    AR  72680      South        bcjin   
3        Knox      Bladensburg    OH  43005    Midwest      loguzzi   
4    Muskegon        Fruitport    MI  49415    Midwest       cchunt   
5     Wyoming      Cowlesville    NY  14037  Northeast 

In [24]:
#tail(): it can retun the data from bottom
df.tail(15)

Emp ID Name Prefix First Name Middle Initial   Last Name Gender  \
49985  475827         Ms.    Beverly              D      Jewell      F   
49986  649810         Mr.       Juan              L       Coury      M   
49987  267565         Ms.     Lenora              S      Kulick      F   
49988  939635        Hon.     Delora              H       Corle      F   
49989  514084       Prof.    Rolando              S   Oestreich      M   
49990  963209        Mrs.      Billy              I     Phillip      F   
49991  931753         Ms.     Grayce              J       Vella      F   
49992  578366        Mrs.   Nicolasa              I      Hearns      F   
49993  481787         Ms.    Estella              N     Gelinas      F   
49994  186184         Mr.     Donald              J  Hunsberger      M   
49995  773461        Hon.     Felton              J        Hohl      M   
49996  743563         Ms.      Launa              N      Staudt      F   
49997  248566         Ms.      Caryl              S      Ezzell      F   
49998  320960         Mr.     Xavier              U     Deberry      M   
49999  508239        Mrs.     Blanch              I    Tarleton      F   

                              E Mail       Father's Name      Mother's Name  \
49985  beverly.jewell@exxonmobil.com      Tristan Jewell     Lucinda Jewell   
49986           juan.coury@gmail.com       Bernard Coury       Alisia Coury   
49987          lenora.kulick@aol.com        Randy Kulick       Kiana Kulick   
49988         delora.corle@gmail.com        Darrin Corle     Michaele Corle   
49989    rolando.oestreich@yahoo.com   Brenton Oestreich   Helene Oestreich   
49990        billy.phillip@gmail.com        Lupe Phillip    Georgie Phillip   
49991         grayce.vella@gmail.com         Ernie Vella       Terrie Vella   
49992    nicolasa.hearns@hotmail.com        Tommy Hearns        Roxy Hearns   
49993      estella.gelinas@gmail.com     Terence Gelinas      Diann Gelinas   
49994      donald.hunsberger@aol.com  Milford Hunsberger  Pinkie Hunsberger   
49995          felton.hohl@yahoo.com        Gustavo Hohl          Eric Hohl   
49996           launa.staudt@aol.com          Dee Staudt     Laurice Staudt   
49997           caryl.ezzell@aol.com      Maxwell Ezzell     Coralie Ezzell   
49998     xavier.deberry@hotmail.com      Alfred Deberry  Jeannette Deberry   
49999   blanch.tarleton@ntlworld.com     Landon Tarleton  Roseanne Tarleton   

      Mother's Maiden Name  ...          SSN    Phone No.       Place Name  \
49985         Dunkelberger  ...  586-67-4772  203-607-0726   Redding Ridge   
49986             Castelli  ...  342-11-8788  701-626-9934        Buchanan   
49987               Furrow  ...  496-29-1863  701-669-9002           Pisek   
49988              Nielsen  ...  385-37-6869  319-323-7435        Stanhope   
49989                 Abad  ...  393-33-2958  210-966-7636         Cee Vee   
49990                 Fava  ...  201-84-2002  212-592-6944        Maybrook   
49991               Markus  ...  594-99-6653  216-363-2159      Cincinnati   
49992            Sotomayor  ...  082-02-2807  215-588-6574    Philadelphia   
49993           Chamberlin  ...  603-87-1791  218-420-9508     Minneapolis   
49994              Seltzer  ...  002-11-0103  215-487-8340     Lake Winola   
49995               Caison  ...  730-28-6986  201-442-3031  Franklin Lakes   
49996              Carnell  ...  241-99-2686  218-337-3165        Cohasset   
49997               Cruise  ...  242-99-2663  215-930-7475       Claysburg   
49998               Hamner  ...  129-98-5613  219-405-5878        Fairland   
49999                 Heim  ...  486-29-5581  505-630-4001   Jemez Springs   

             County            City State    Zip     Region     User Name  \
49985     Fairfield   Redding Ridge    CT   6876  Northeast      bdjewell   
49986      Stutsman        Buchanan    ND  58420    Midwest       jlcoury   
49987         Walsh           Pisek    ND  58273    Midwest      lskulick   


In [25]:
#describe(): (its performs the counting, means,std,min,max and percebtile of the dataset.)
df.describe()

Emp ID   Age in Yrs.  Weight in Kgs.  Year of Joining  \
count   50000.000000  50000.000000    50000.000000     50000.000000   
mean   555457.763620     40.561104       59.982920      2007.306600   
std    255906.633279     11.272835       13.711586         8.602125   
min    111112.000000     21.000000       40.000000      1978.000000   
25%    334764.250000     30.790000       50.000000      2002.000000   
50%    554324.500000     40.560000       57.000000      2010.000000   
75%    776663.250000     50.340000       70.000000      2014.000000   
max    999982.000000     60.000000       90.000000      2017.000000   

       Month of Joining  Day of Joining  Age in Company (Years)  \
count      50000.000000    50000.000000            50000.000000   
mean           6.480380       15.736820                9.775455   
std            3.415472        8.780311                8.596988   
min            1.000000        1.000000                0.000000   
25%            4.000000        8.000000                2.680000   
50%            6.000000       16.000000                7.320000   
75%            9.000000       23.000000               14.940000   
max           12.000000       31.000000               38.700000   

              Salary           Zip  
count   50000.000000  50000.000000  
mean   120265.632920  49768.949760  
std     46233.935072  27767.576807  
min     40002.000000    210.000000  
25%     80215.000000  26301.750000  
50%    120201.500000  48787.000000  
75%    160361.250000  73073.250000  
max    199998.000000  99950.000000

In [31]:
#Slicing the Data:(you can use the coloumn name to extract data in a particular column)
#df[["Emp ID","Salary"]]
df[0:5]
df[0:50]

Emp ID Name Prefix First Name Middle Initial   Last Name Gender  \
0   158108         Mr.    Bernard              N   Weatherly      M   
1   863655         Ms.     Cordia              M       Knopp      F   
2   343966         Mr.     Burton              C         Jin      M   
3   389958         Mr.     Lauren              O       Guzzi      M   
4   291208       Prof.     Carter              C        Hunt      M   
5   636449         Mr.     Isaiah              Y     Magwood      M   
6   731529         Mr.       Hugh              N     Chavira      M   
7   331652       Prof.     Lucius              C    Moorhead      M   
8   930753         Ms.      Deane              I       Keown      F   
9   212822        Mrs.    Joannie              E     Wolters      F   
10  406273         Ms.  Christene              L     Mccaleb      F   
11  984721        Mrs.     Alline              V     Kushner      F   
12  161868        Hon.      Vicki              Y    Hargrave      F   
13  948514        Mrs.   Julienne              A      Merkel      F   
14  467644         Mr.      Keven              C       Thole      M   
15  439713         Ms.    Eusebia              N    Waldroup      F   
16  435127         Ms.  Veronique              E   Eccleston      F   
17  880688        Mrs.       Sean              W     Richman      F   
18  415263         Ms.       Lala              C     Marquez      F   
19  697769        Hon.     Derick              A       Macey      M   
20  469336        Mrs.        Eda              O       Brase      F   
21  352932         Mr.     Willis              D    Weissman      M   
22  829478         Ms.     Mariam              F    Pinheiro      F   
23  517840         Mr.     Malcom              L     Meister      M   
24  709861        Mrs.      Holli              G    Ethridge      F   
25  751367         Dr.       Cole              N      Poling      M   
26  940813         Dr.      Ahmad              V       Lynde      M   
27  930580         Dr.    Mariano              F       Leary      M   
28  120297         Ms.    Tawanda              E    Buchanon      F   
29  796317        Hon.   Nickolas              G      Grossi      M   
30  866076         Mr.   Bradford              K     Marlatt      M   
31  307787       Prof.    Carlton              P        Bose      M   
32  307470        Mrs.   Asuncion              X  Braunstein      F   
33  167307         Mr.     Theron              T      Kramer      M   
34  511136       Prof.     Jeramy              F     Metoyer      M   
35  320739        Hon.        Sol              K       Roger      F   
36  979767         Mr.    Earnest              H    Birkholz      M   
37  683618         Ms.      Amada              J      Knouse      F   
38  473705         Mr.   Gregorio              H   Hottinger      M   
39  565194         Mr.  Lawerence              W   Abernethy      M   
40  961028         Ms.     Marina              X      Quayle      F   
41  595955         Mr.    Whitney              N    Wasinger      M   
42  501666       Prof.        Roy              W      Wilkie      M   
43  519722         Ms.       Hyun              Z       Bynoe      F   
44  315542         Ms.    Katelin              F       Coney      F   
45  655893        Mrs.   Jennifer              Z     Pridgen      F   
46  840300         Mr.    Zachary              U     Breeden      M   
47  837373         Mr.       Deon              U      Mounce      M   
48  917497         Dr.      Buddy              G   Steinbeck      M   
49  629761         Dr.     Julius              N      Bakker      M   

                               E Mail        Father's Name  \
0         bernard.weatherly@gmail.com     Wilbur Weatherly   
1            cordia.knopp@hotmail.com         Wilson Knopp   
2                burton.jin@yahoo.com          Richard Jin   
3              lauren.guzzi@yahoo.com          Blair Guzzi   
4             carter.hunt@hotmail.com           Jamal Hunt   
5         

In [37]:
#loc(): This function is used to select multiple columns by names.
#mul col
df.loc[:,["Emp ID","Salary","E Mail"]]
#mUL row - iloc():
#df.iloc[:5,:5]

Emp ID  Salary                         E Mail
0      158108   81323    bernard.weatherly@gmail.com
1      863655  169367       cordia.knopp@hotmail.com
2      343966  142688           burton.jin@yahoo.com
3      389958  100371         lauren.guzzi@yahoo.com
4      291208  104383        carter.hunt@hotmail.com
5      636449  171165     isaiah.magwood@comcast.net
6      731529  124363          hugh.chavira@yahoo.ca
7      331652   74133      lucius.moorhead@yahoo.com
8      930753  146728        deane.keown@hotmail.com
9      212822  193233    joannie.wolters@yahoo.co.in
10     406273  130856    christene.mccaleb@gmail.com
11     984721  196569         alline.kushner@aol.com
12     161868  193680     vicki.hargrave@hotmail.com
13     948514  129602    julienne.merkel@hotmail.com
14     467644  130067          keven.thole@gmail.com
15     439713  173975   eusebia.waldroup@hotmail.com
16     435127   56343    veronique.eccleston@aol.com
17     880688   76964         sean.richman@yahoo.com
18     415263  121928           lala.marquez@aol.com
19     697769   96558       derick.macey@walmart.com
20     469336  154102        eda.brase@earthlink.net
21     352932   67163      willis.weissman@gmail.com
22     829478  140901      mariam.pinheiro@gmail.com
23     517840  110929       malcom.meister@apple.com
24     709861   97123       holli.ethridge@gmail.com
25     751367  159702        cole.poling@hotmail.com
26     940813  138480          ahmad.lynde@gmail.com
27     930580  132605          mariano.leary@aol.com
28     120297  188854     tawanda.buchanon@gmail.com
29     796317   94238        nickolas.grossi@aol.com
...       ...     ...                            ...
49970  786901  179135        stewart.mantz@gmail.com
49971  279036   50248       dewitt.ekstrom@gmail.com
49972  525884   77093         candyce.gardea@aol.com
49973  226692  146003           ezra.loman@gmail.com
49974  189099   40944         raymundo.hagar@aol.com
49975  162936  161109         norberto.basham@bp.com
49976  602698   55646       desire.keefe@comcast.net
49977  144035  116944         serena.fussell@aol.com
49978  215934  128314     william.amen@bellsouth.net
49979  968064   98414       ginette.holden@gmail.com
49980  197081  165487                pei.fey@msn.com
49981  887146   62149        leanne.uecker@gmail.com
49982  518937  148519              jarod.rech@bp.com
49983  684273  190340          hiroko.holton@aol.com
49984  283912  112093        theo.blanford@gmail.com
49985  475827   75182  beverly.jewell@exxonmobil.com
49986  649810  110865           juan.coury@gmail.com
49987  267565  178965          lenora.kulick@aol.com
49988  939635   79224         delora.corle@gmail.com
49989  514084   94764    rolando.oestreich@yahoo.com
49990  963209  169191        billy.phillip@gmail.com
49991  931753  172777         grayce.vella@gmail.com
49992  578366  111423    nicolasa.hearns@hotmail.com
49993  481787  157271      estella.gelinas@gmail.com
49994  186184  184366      donald.hunsberger@aol.com
49995  773461  199167          felton.hohl@yahoo.com
49996  743563  176510           launa.staudt@aol.com
49997  248566   49236           caryl.ezzell@aol.com
49998  320960  126789     xavier.deberry@hotmail.com
49999  508239  116935   blanch.tarleton@ntlworld.com

[50000 rows x 3 columns]

In [45]:
#Drop a Column: (you can drop columns using pd.drop())
#df.drop(columns=["Emp ID","Salary"])
#sort the values:
df.sort_values("Salary")
df.sort_values("Emp ID")

In [53]:
#rename: change of Index name:
df1=df.rename(columns={"Emp ID":"MY ID","Salary":"Credit","E Mail":"G Mail"})
df1

MY ID Name Prefix First Name Middle Initial   Last Name Gender  \
0      158108         Mr.    Bernard              N   Weatherly      M   
1      863655         Ms.     Cordia              M       Knopp      F   
2      343966         Mr.     Burton              C         Jin      M   
3      389958         Mr.     Lauren              O       Guzzi      M   
4      291208       Prof.     Carter              C        Hunt      M   
5      636449         Mr.     Isaiah              Y     Magwood      M   
6      731529         Mr.       Hugh              N     Chavira      M   
7      331652       Prof.     Lucius              C    Moorhead      M   
8      930753         Ms.      Deane              I       Keown      F   
9      212822        Mrs.    Joannie              E     Wolters      F   
10     406273         Ms.  Christene              L     Mccaleb      F   
11     984721        Mrs.     Alline              V     Kushner      F   
12     161868        Hon.      Vicki              Y    Hargrave      F   
13     948514        Mrs.   Julienne              A      Merkel      F   
14     467644         Mr.      Keven              C       Thole      M   
15     439713         Ms.    Eusebia              N    Waldroup      F   
16     435127         Ms.  Veronique              E   Eccleston      F   
17     880688        Mrs.       Sean              W     Richman      F   
18     415263         Ms.       Lala              C     Marquez      F   
19     697769        Hon.     Derick              A       Macey      M   
20     469336        Mrs.        Eda              O       Brase      F   
21     352932         Mr.     Willis              D    Weissman      M   
22     829478         Ms.     Mariam              F    Pinheiro      F   
23     517840         Mr.     Malcom              L     Meister      M   
24     709861        Mrs.      Holli              G    Ethridge      F   
25     751367         Dr.       Cole              N      Poling      M   
26     940813         Dr.      Ahmad              V       Lynde      M   
27     930580         Dr.    Mariano              F       Leary      M   
28     120297         Ms.    Tawanda              E    Buchanon      F   
29     796317        Hon.   Nickolas              G      Grossi      M   
...       ...         ...        ...            ...         ...    ...   
49970  786901         Mr.    Stewart              Z       Mantz      M   
49971  279036       Prof.     Dewitt              U     Ekstrom      M   
49972  525884         Ms.    Candyce              Z      Gardea      F   
49973  226692         Mr.       Ezra              P       Loman      M   
49974  189099         Mr.   Raymundo              T       Hagar      M   
49975  162936         Mr.   Norberto              X      Basham      M   
49976  602698        Mrs.     Desire              R       Keefe      F   
49977  144035        Hon.     Serena              X     Fussell      F   
49978  215934        Hon.    William              Z        Amen      M   
49979  968064         Ms.    Ginette              Z      Holden      F   
49980  197081         Ms.        Pei              D         Fey      F   
49981  887146        Drs.     Leanne              J      Uecker      F   
49982  518937         Mr.      Jarod              C        Rech      M   
49983  684273         Ms.     Hiroko              L      Holton      F   
49984  283912         Mr.       Theo              T    Blanford      M   
49985  475827         Ms.    Beverly              D      Jewell      F   
49986  649810         Mr.       Juan              L       Coury      M   
49987  267565         Ms.     Lenora              S      Kulick      F   
49988  939635        Hon.     Delora              H       Corle      F   
49989  514084       Prof.    Rolando              S   Oestreich      M   
49990  963209        Mrs.      Billy              I     Phillip      F   
49991  931753         Ms.     Grayce              J       Vella      F   
49992  57836

In [23]:
#random sequence: (user created Data Frame)
import numpy as np
import pandas as pd
random = np.random.randn(6,4)
random1 = np.random.randn(6,4)

normal = np.array([[1,2,3,4,5,6],[6,7,8,9]])

df = pd.DataFrame(random,index=["A","B","C","D","E","F"],columns=list('ABCD'))

df2 = pd.DataFrame(normal)
df3 = pd.DataFrame(random1,index=["A","B","C","D","E","F"],columns=list('AXYZ'))
print(df)
print(df.head(3))
print(df.tail(3))
print(df.describe())
print(df[0:5])
print(df+df3)

          A         B         C         D
A  0.897205  1.095330  0.481321  0.173243
B  0.546013 -1.389014  0.771836  0.171945
C -0.478982 -0.665200  0.252498 -1.116795
D  0.665520  0.532133  0.010674 -1.472808
E  0.125223  0.260278  0.595309 -0.081466
F -0.208724 -0.862542  1.414820 -0.624277
          A         B         C         D
A  0.897205  1.095330  0.481321  0.173243
B  0.546013 -1.389014  0.771836  0.171945
C -0.478982 -0.665200  0.252498 -1.116795
          A         B         C         D
D  0.665520  0.532133  0.010674 -1.472808
E  0.125223  0.260278  0.595309 -0.081466
F -0.208724 -0.862542  1.414820 -0.624277
              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.257709 -0.171502  0.587743 -0.491693
std    0.535950  0.947630  0.484712  0.695954
min   -0.478982 -1.389014  0.010674 -1.472808
25%   -0.125237 -0.813207  0.309704 -0.993665
50%    0.335618 -0.202461  0.538315 -0.352871
75%    0.635644  0.464170  0.727705  0.108592
ma